### ISSUE TITLE
ReferenceError: div is not defined

### ISSUE THREAD

**Issue by amirhoseinsalimi** [matyunya/smelte#95]
Hi,

The following example from the docs:

```
<script>
	import Button from 'components/Button';
	import Menu from 'components/Menu';
	import List from 'components/List';

  let open = true;
	let selected = "";

  const items = [
		{ value: 1, text: 'One' },
		{ value: 2, text: 'Two' },
		{ value: 3, text: 'Three' },
		{ value: 4, text: 'Four' },
		{ value: 5, text: 'Five' },
	];

</script>

<small>Selected: {selected || 'nothing'}</small>

<Menu bind:open {items} bind:value={selected}>
	<div slot="activator">
		<Button on:click={() => open = !open}>A menu</Button>
	</div>
</Menu>
```
throws the error:

```
Uncaught (in promise) ReferenceError: div is not defined
    at Object.update [as p] (Menu.svelte:47)
    at Object.update [as p] (Menu.svelte:44)
    at update (index.mjs:687)
    at flush (index.mjs:656)
```

I can't find why is that happening?

**Comment by shanna** [comment]
I hit the same issue. After some searching it appears to be an upstream bug in svelte 3.20.0 and that 3.20.1 attempted to fix but did not.

3.19.2 is the last known working version so I've pinned my project to that till the bug is fixed.

See:
https://github.com/sveltejs/svelte/issues/4597
https://github.com/sveltejs/svelte/issues/4562

**Comment by amirhoseinsalimi** [comment]
Thank ya, that worked. I fixed my version to that specific version and the error is gone. So I close this issue is regarding Svelte.
